HorizonsEndMC/Ion

src/main/kotlin/net/horizonsend/ion/MiscellaneousListeners.kt
Wasn't able to test this, but it should work.
=> Disable chorus and ender pearl teleporting

src/main/kotlin/net/horizonsend/ion/Ion.kt
=> Bell recipe

src/main/kotlin/net/horizonsend/ion/features/ores/OreListener.kt, src/main/kotlin/net/horizonsend/ion/features/ores/OrePlacementConfig.kt
=> Fix Peters bad code

Server/src/main/kotlin/net/horizonsend/ion/server/listeners/bukkit/PlayerDeathListener.kt
=> PlayerKillAchievment

Server/src/main/kotlin/net/starlegacy/feature/starship/StarshipType.kt
removes the poweroverride which makes the ships literally unable to do anything and basically a platform class with a fancy name like bro just lemme use the ships 🙏 🙏 🙏
=> make the BC -> Supercap classes actually function

Server/src/main/kotlin/net/starlegacy/feature/starship/StarshipType.kt
destroyers can now fire and move lol
=> Fix destroyers having 0 power

Server/src/main/kotlin/net/starlegacy/feature/misc/DecomposeTask.kt
Tested- gives custom blocks but not ores. Should automatically count any future ores added. Also fixed some depreciations.
=> Decomp fix

Server/src/main/kotlin/net/horizonsend/ion/server/Crafting.kt
Adds nether wart block -> 9x nether warts recipe, a vanilla recipe already exists for 9x nether warts -> nether wart block.
=> Nether wart crafting

Server/src/main/kotlin/net/starlegacy/feature/starship/movement/OptimizedMovement.kt
the server can handle it now (and could before)
=> enable lighting updates

Server/src/main/kotlin/net/starlegacy/feature/multiblock/Multiblocks.kt, Server/src/main/kotlin/net/starlegacy/feature/multiblock/dockingtube/ConnectedDockingTubeMultiblock.kt, Server/src/main/kotlin/net/starlegacy/feature/multiblock/dockingtube/DisconnectedDockingTubeMultiblock.kt, Server/src/main/kotlin/net/starlegacy/feature/multiblock/dockingtube/DockingTubeMultiblock.kt, Server/src/main/kotlin/net/starlegacy/listener/misc/InteractListener.kt
+ fix a bunch of depreciations
=> fix docking tubes

Server/src/main/kotlin/net/starlegacy/feature/chat/ChannelSelections.kt
dix deprications (that "action" strikethrough thing) and changed the color code/italize/bold thing from "&f&l" to "<white><bold>"
=> Undepreication practice

Server/src/main/kotlin/net/starlegacy/feature/starship/PilotedStarships.kt
=> Probably a fix to the captain uuid name thing

server/src/main/kotlin/net/horizonsend/ion/server/Crafting.kt
=> Created recipes for all 3 froglights

server/src/main/kotlin/net/horizonsend/ion/server/BalancingConfiguration.kt, server/src/main/kotlin/net/horizonsend/ion/server/items/CustomItems.kt
Updated the model data for the new blasters and renamed the auto rifle to smg
=> Updated model data + Renamed auto rifle

server/src/main/kotlin/net/starlegacy/command/progression/AdvanceAdminCommand.kt, server/src/main/kotlin/net/starlegacy/command/progression/XPCommand.kt
Tested and verified on Project Echelon
=> removed deprecations in kotlin/net/starlegacy/command/progression

server/src/main/kotlin/net/starlegacy/command/misc/BatteryCommand.kt, server/src/main/kotlin/net/starlegacy/command/misc/CustomItemCommand.kt, server/src/main/kotlin/net/starlegacy/command/misc/DyeCommand.kt, server/src/main/kotlin/net/starlegacy/command/misc/GToggleCommand.kt, server/src/main/kotlin/net/starlegacy/command/misc/GlobalGameRuleCommand.kt, server/src/main/kotlin/net/starlegacy/command/misc/ListCommand.kt, server/src/main/kotlin/net/starlegacy/command/misc/ShuttleCommand.kt, server/src/main/kotlin/net/starlegacy/command/misc/TransportDebugCommand.kt
Fixed as many deprecations as possible in commands/misc
=> Commands misc deprecations

server/src/main/kotlin/net/horizonsend/ion/server/legacy/feedback/Feedback.kt, server/src/main/kotlin/net/starlegacy/command/misc/ListCommand.kt, server/src/main/kotlin/net/starlegacy/command/space/SpaceWorldCommand.kt, server/src/main/kotlin/net/starlegacy/listener/nations/MovementListener.kt
Tested and verified on Project Echelon
=> sendFeedbackTitle() & removed Territory Deprecations

server/src/main/kotlin/net/starlegacy/command/starship/MiscStarshipCommands.kt, server/src/main/kotlin/net/starlegacy/feature/multiblock/hyperdrive/HyperdriveMultiblock.kt
Tested and verified on Project Echelon
=> Improved Hyperdrive User Experience

server/src/main/kotlin/net/starlegacy/listener/gear/DoubleJumpListener.kt
Should fix the following issue:
https://user-images.githubusercontent.com/66213737/219259484-a6aa5d10-af64-437d-9765-313eb430b820.mp4
This is untested, as I really can't be bothered to set up docker and such for the testing server for just this tiny fix.
=> Improve double-jump ground check

gradle/libs.versions.toml, proxy/build.gradle.kts, proxy/src/main/kotlin/net/horizonsend/ion/proxy/IonProxy.kt, proxy/src/main/kotlin/net/horizonsend/ion/proxy/Utilities.kt, proxy/src/main/kotlin/net/horizonsend/ion/proxy/commands/waterfall/MessageCommand.kt
=> Proxy-wide /msg & /r

server/src/main/kotlin/net/starlegacy/command/starship/MiscStarshipCommands.kt, server/src/main/kotlin/net/starlegacy/feature/starship/hyperspace/MassShadows.kt
Added clarifying details for a ship attempting to jump within a gravity well. Tested and verified on Project Echelon.
=> Added details to the /jump gravity well user error message

server/src/main/kotlin/net/starlegacy/feature/starship/active/ActiveStarshipMechanics.kt, server/src/main/kotlin/net/starlegacy/feature/starship/subsystem/weapon/TurretWeaponSubsystem.kt, server/src/main/kotlin/net/starlegacy/feature/starship/subsystem/weapon/projectile/SimpleProjectile.kt
=> Async turrets ft. tears

server/src/main/kotlin/net/starlegacy/feature/starship/FlyableBlocks.kt
added fence gates, more anvils, crafting stations, froglights, campfires, soul variants, beehive, all heads, lightning rod.
=> Added blocks to flyable list pls dont reject it

server/src/main/kotlin/net/starlegacy/feature/starship/FlyableBlocks.kt, server/src/main/kotlin/net/starlegacy/feature/starship/factory/StarshipFactories.kt
Tested and verified on Project Echelon
=> Starship factory fixes

server/src/main/kotlin/net/starlegacy/feature/starship/active/ActiveStarshipMechanics.kt, server/src/main/kotlin/net/starlegacy/feature/starship/subsystem/weapon/TurretWeaponSubsystem.kt, server/src/main/kotlin/net/starlegacy/feature/starship/subsystem/weapon/projectile/SimpleProjectile.kt
=> Revert "Async turrets ft. tears"

common/build.gradle.kts, common/src/main/kotlin/net/horizonsend/ion/common/Connectivity.kt, common/src/main/kotlin/net/horizonsend/ion/common/database/Collection.kt, common/src/main/kotlin/net/horizonsend/ion/common/database/Document.kt, common/src/main/kotlin/net/horizonsend/ion/common/database/PlayerAchievement.kt, common/src/main/kotlin/net/horizonsend/ion/common/database/PlayerData.kt, common/src/main/kotlin/net/horizonsend/ion/common/database/PlayerVoteTime.kt, common/src/main/kotlin/net/horizonsend/ion/common/database/collections/PlayerData.kt, proxy/src/main/kotlin/net/horizonsend/ion/proxy/commands/discord/DiscordAccountCommand.kt, proxy/src/main/kotlin/net/horizonsend/ion/proxy/commands/waterfall/BungeeAccountCommand.kt, proxy/src/main/kotlin/net/horizonsend/ion/proxy/commands/waterfall/VoteCommand.kt, proxy/src/main/kotlin/net/horizonsend/ion/proxy/listeners/waterfall/ServerConnectListener.kt, proxy/src/main/kotlin/net/horizonsend/ion/proxy/listeners/waterfall/VotifierListener.kt, proxy/src/main/kotlin/net/horizonsend/ion/proxy/managers/ReminderManager.kt, proxy/src/main/kotlin/net/horizonsend/ion/proxy/managers/SyncManager.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/achievements/AchievementListeners.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/achievements/Achievements.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/achievements/AchievementsCommand.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/achievements/AchievementsScreen.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/blasters/SettingsCommand.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/blasters/objects/Blaster.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/bounties/Bounty.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/bounties/BountyCommands.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/bounties/BountyListener.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/bounties/BountyScreen.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/listeners/MiscListeners.kt, server/src/main/kotlin/net/starlegacy/feature/progression/ShipKillXP.kt
=> Moving everything to SQL

server/src/main/kotlin/net/starlegacy/feature/starship/movement/TranslateMovement.kt
This is untested. I don't know if it will work, or if the teleportation statement I edited is even the correct one. 
See https://discord.com/channels/916891217596395631/946437988806688858/1085005231529676840
=> Add RETAIN_OPEN_INVENTORY teleport flag to TranslateMovement

server/src/main/kotlin/net/starlegacy/command/starship/MiscStarshipCommands.kt, server/src/main/kotlin/net/starlegacy/feature/starship/hyperspace/Hyperspace.kt
=> hyperdrive tier specification

server/src/main/kotlin/net/starlegacy/feature/starship/subsystem/weapon/projectile/SimpleProjectile.kt
=> fix the fix of projectiles in hyperspace

server/src/main/kotlin/net/starlegacy/feature/transport/Extractors.kt, server/src/main/kotlin/net/starlegacy/feature/transport/Wires.kt
Inverted solar panels will now generate 50% power when not in the overworld and in the darkness
This is untested, as I'm too lazy to set up a test server.
Requested by Vandrayk
=> Let inverted solar panels work in space

server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/listeners/GameplayTweaksListeners.kt
Fixes ticket 233
Untested, as I'm too lazy to set up a test server, but if this doesn't work I'll be surprised... its a one line change.
=> Fix undetected crate check spamming chat

server/src/main/kotlin/net/starlegacy/command/starship/MiscStarshipCommands.kt
=> Display grace protection star next to player's name in /listships

server/src/main/kotlin/net/horizonsend/ion/server/features/starship/mininglaser/MiningLaserSubsystem.kt
=> Alert when mining laser isn't mining anything

server/src/main/kotlin/net/starlegacy/command/starship/MiscStarshipCommands.kt
- forgot to specify world name
=> jump command fix

server/src/main/kotlin/net/starlegacy/command/nations/SettlementCommand.kt
- see earlier nation command fix
=> settlement command fix

server/src/main/kotlin/net/starlegacy/command/starship/MiscStarshipCommands.kt
=> fix star next to listships

server/src/main/kotlin/net/horizonsend/ion/server/configuration/BalancingConfiguration.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/blasters/RayTracedParticleProjectile.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/blasters/objects/Blaster.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/customitems/CustomItems.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/customitems/commands/ConvertCommand.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/Crafting.kt
=> Blaster Cannon

server/src/main/kotlin/net/horizonsend/ion/server/features/machine/GeneratorFuel.kt
=> uranium buff

server/src/main/kotlin/net/horizonsend/ion/server/features/misc/GameplayTweaks.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/Mass.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/utils/Materials.kt
Is it wrong that I'm doing this bc I use the original anvil mass on survival...
=> Make anvils 6000 mass but keep 6.0 mass

server/src/main/kotlin/net/horizonsend/ion/server/features/starship/StarshipType.kt
Discussed in #projects of HE Discord
=> T1 Mining Laser for Corvette, Frigate, Destroyer

server/src/main/kotlin/net/horizonsend/ion/server/features/starship/Interdiction.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/control/StarshipControl.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/control/StarshipCruising.kt
- Gravity Well cannot be activated while cruising
- Gravity well can now be activated while in Direct Control
=> Gravity Well Changes

server/src/main/kotlin/net/horizonsend/ion/server/configuration/StarshipTypeBalancing.kt
pulse cannon power usage on corvettes 2.4k -> 2.55k tri turret minBlockCount = 3400
=> last minute corvette balancing

server/src/main/kotlin/net/horizonsend/ion/server/features/client/networking/Packets.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/client/networking/packets/WorldPacket.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Listeners.kt
Packet for void to detect when a world has changed, so it can change the skybox accordingly
=> Void Change World packet

server/src/main/kotlin/net/horizonsend/ion/server/configuration/StarshipTypeBalancing.kt
minimum size for LT remains 1750 with a hard minsize cap (no fun for gigajeff)
=> make sure min size LT stays the same as before

server/src/main/kotlin/net/horizonsend/ion/server/features/customblocks/CustomBlockListeners.kt, server/src/main/kotlin/net/horizonsend/ion/server/listener/gear/PowerToolListener.kt
- Fixed custom blocks ignoring territory permissions
=> Custom Block Hotfix #3 (or so)

proxy/src/main/kotlin/net/horizonsend/ion/proxy/managers/ReminderManager.kt
i highly suggest randomizing these in-game ^^^
=> fix typos, reword messages, & add more

server/src/main/kotlin/net/horizonsend/ion/server/features/customblocks/CustomBlocks.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/customitems/CustomItems.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Crafting.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/ShipFactoryMaterialCosts.kt
New blocks:
- Raw Aluminum Block
- Raw Titanium Block
- Raw Uranium Block
Can be crafted into raw ore variant and back
=> Add raw ore blocks

server/src/main/kotlin/net/horizonsend/ion/server/configuration/StarshipTypeBalancing.kt
BC speed 8 bps -> 12 (too slow to justify cost)
=> final BC speed buff

server/src/main/kotlin/net/horizonsend/ion/server/features/chat/ChatChannel.kt
it was conflicting with ally chat too much lol
=> make staff chat blue

server/src/main/kotlin/net/horizonsend/ion/server/command/qol/FixExtractorsCommand.kt, server/src/main/kotlin/net/horizonsend/ion/server/command/qol/SetPowerCommand.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Commands.kt
and now, everything is done the right way
=> Added /setpower command, added helpful checks to /fixextractors

server/src/main/kotlin/net/horizonsend/ion/server/command/starship/MiscStarshipCommands.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/Interdiction.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/active/SubsystemDetector.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/subsystem/shield/StarshipShields.kt
- If a starship shield is set to 0% health by incoming damage, it will no longer absorb the explosion
- Added multiblock check for `/gravwell` command
=> Balancing Changes

server/src/main/kotlin/net/horizonsend/ion/server/features/misc/GameplayTweaks.kt
IDK if I did this right AAAAAAAAAAA.
(makes lapis as resistant as other blocks so it can be used on ship hulls and such decoratively)
=> Lapis Blast Resistance

common/src/main/kotlin/net/horizonsend/ion/common/extensions/Audience.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/drills/DrillMultiblock.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/PilotedStarships.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/active/ActiveStarshipFactory.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/active/ActiveStarshipMechanics.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/subsystem/MiningLaserSubsystem.kt
also added some functions for Title & Subtitle in Audience.kt
=> fix up some chat spam

server/src/main/kotlin/net/horizonsend/ion/server/command/misc/MultiblockCommand.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/client/whereisit/SearchCommand.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/space/encounters/CoolantLeak.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/space/encounters/DefuseBomb.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/utils/Miscellaneous.kt
- `/multiblock check` spawns display entity blocks of the expected block
- backend changes to `highlightBlock()`
=> highlight block improvements (feat. display entities)

server/src/main/kotlin/net/horizonsend/ion/server/command/starship/MiscStarshipCommands.kt
/listships player = active player starships
/listships ai = active ai starships
/listships = both ai and player starships
First coding experience I'm so happy
=> Added options to listships

server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/legacy/CustomRecipes.kt
4 red terracotta, 4 dark prismarine, 1 turtle egg
=> sniffer egg recipe

server/src/main/kotlin/net/horizonsend/ion/server/features/client/display/ClientDisplayEntities.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/client/display/PlanetSpaceRendering.kt
minor changes; little to no visual effect
=> Planets In Space Hotfix

common/src/main/kotlin/net/horizonsend/ion/common/database/cache/nations/PlayerCache.kt, common/src/main/kotlin/net/horizonsend/ion/common/database/schema/misc/SLPlayer.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/client/commands/HudCommand.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/client/display/PlanetSpaceRendering.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Commands.kt
- Added commands to enable/disable planets in HUD `/hud planets <image/selector> <true/false>`
- Fixed potential z-fighting issues
=> Planets in space Hotfix 2

run/config/waterfall/config.yml, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/misc/FuelTankMultiblock.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/starshipweapon/turret/IonTurretMultiblock.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/supercapreactor/SupercapReactorMultiblock.kt
…with the ion turret's multiblock
=> cooler reactor and fuel tank signs, fix a big with ion turret multiblock

run/config/waterfall/config.yml, server/src/main/kotlin/net/horizonsend/ion/server/configuration/StarshipTypeBalancing.kt
too tired to explain, cruiser OP BC superduper OP
=> ion turret and bc balancing

server/src/main/kotlin/net/horizonsend/ion/server/configuration/StarshipTypeBalancing.kt
juicing these supercaps up to the gills for testing
=> putting BCs on roids

server/src/main/kotlin/net/horizonsend/ion/server/IonServer.kt, server/src/main/kotlin/net/horizonsend/ion/server/command/GlobalCompletions.kt, server/src/main/kotlin/net/horizonsend/ion/server/command/qol/ContainerCommand.kt, server/src/main/kotlin/net/horizonsend/ion/server/command/qol/FixExtractorsCommand.kt, server/src/main/kotlin/net/horizonsend/ion/server/command/qol/SetPowerCommand.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Commands.kt
commands:
/container empty - clears all contents of selected containers
/container empty (anyItem) - clears anyItem from selected containers
/container fill (anyItem) - fills selected containers with anyItem, at its maximum stack size
=> added /container empty/fill command

server/src/main/kotlin/net/horizonsend/ion/server/configuration/StarshipTypeBalancing.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/customblocks/CustomBlocks.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/customitems/CustomItems.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/MultiblockShape.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/Multiblocks.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/supercapreactor/BCReactorMultiblock.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/supercapreactor/CruiserReactorMultiblock.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/PilotedStarships.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/StarshipType.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/active/ActiveStarshipMechanics.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/active/SubsystemDetector.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/destruction/BattlecruiserSink.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/destruction/CruiserSink.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/destruction/SinkProvider.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/hyperspace/Hyperspace.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/hyperspace/HyperspaceWarmup.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/subsystem/BCReactorSubsystem.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/subsystem/CruiserReactorSubsystem.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/subsystem/SupercapReactorSubsystem.kt, server/src/main/kotlin/net/horizonsend/ion/server/listener/fixers/CancelListeners.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Crafting.kt
Give Cruisers a reactor, rewrite lots of BC reactor specific stuff to be BCs and Cruisers, cruisers have a sink function that is currently identical to BCs, change turret shell recipe
=> Cruiser reactor and turret ammo recipe change

server/src/main/kotlin/net/horizonsend/ion/server/configuration/StarshipTypeBalancing.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/hyperspace/Hyperspace.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/subsystem/weapon/projectile/ArsenalRocketProjectile.kt
=> arsenal rocket sounds, lots of sounds, all sounds, class specific AR balancing

server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Crafting.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/legacy/CustomRecipes.kt
- Sniffer egg recipe was fixed (found in wrong file, refer to Solesey's recipe)
- Gilded blackstone recipe was added (uses 5 gold nuggets and 4 blackstone in the shape of TNT)
=> Recipe Fix & Addition

server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/ammo/AmmoLoaderMultiblock.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/crafting/MultiblockRecipes.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/PilotedStarships.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/destruction/BattlecruiserSink.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/destruction/CruiserSink.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/subsystem/weapon/projectile/ArsenalRocketProjectile.kt
(Code) Sounds for: Plate Press, Circuit Fab, Centrifuge, Ammo Loader, Missile Loader, Compressor, Fabricator
=> Industry Sounds

server/src/main/kotlin/net/horizonsend/ion/server/features/customitems/CustomItems.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/crafting/MultiblockRecipes.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Crafting.kt
- rename "Enhanced Circuitry" to "Circuit Board"; "Advanced Circuitry" to "Motherboard"
=> minor changes

server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/ammo/AmmoLoaderMultiblock.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/crafting/MultiblockRecipes.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Crafting.kt
-Fix Ammo Loader Multiblock
-Fix Cruiser Recipe
-Change Ammo Recipes
-Fix power draw of machines
-Fix time of industry multi's
-Cheapen arsenal missile slightly (was WAY too expensive)
=> Fixing Felloffbridge Code part 1 morbillion (Various BC changes)

server/src/main/kotlin/net/horizonsend/ion/server/features/starship/subsystem/weapon/primary/QuadTurretWeaponSubsystem.kt
made this in github editor might not work
=> make quad turrets consume ammo (VANDRAYK's fault it was removed)

proxy/src/main/kotlin/net/horizonsend/ion/proxy/managers/ReminderManager.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Crafting.kt
- Unloaded shell crafting quantity 4 -> 1
- Uncharged shell crafting quantity 4 -> 1
- Updated tips messages
- Swap the recipes for Reactive Housing and Reactive Component
=> Supercapital hotfix

server/src/main/kotlin/net/horizonsend/ion/server/features/starship/StarshipType.kt
It is now Sea Lantern and no longer identical to that of Battlecruiser
Yes
=> Update StarshipType.kt Change Barge Icon

server/src/main/kotlin/net/horizonsend/ion/server/features/starship/movement/StarshipMovement.kt
gutin code bro forgot hyperspace worlds arent space worlds
=> allow BCs and barges to enter hyperspace

server/src/main/kotlin/net/horizonsend/ion/server/features/starship/movement/StarshipMovement.kt
need to be lobotomised ASAP sub zero iq
=> fix logic error stopping BCs and barges jumping

server/src/main/kotlin/net/horizonsend/ion/server/configuration/StarshipTypeBalancing.kt
=> Battleships and Dreadnoughts Parity Fix

server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/Multiblocks.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/mininglasers/MiningLaserMultiblockTier1.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/mininglasers/MiningLaserMultiblockTier2.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/mininglasers/MiningLaserMultiblockTier3.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/mininglasers/MiningLaserMultiblockTier4.kt
new lasers do not break existing ones.
=> horizonal mining lasers

server/src/main/kotlin/net/horizonsend/ion/server/features/starship/StarshipType.kt
=> Increase Platform Maximum Size

server/src/main/kotlin/net/horizonsend/ion/server/features/starship/control/signs/StarshipSigns.kt
[directcontrol] or [dc]. Player enters DC at their current position when right clicked.
=> Direct Control Sign

common/src/main/kotlin/net/horizonsend/ion/common/database/cache/nations/PlayerCache.kt, common/src/main/kotlin/net/horizonsend/ion/common/database/schema/misc/SLPlayer.kt, server/src/main/kotlin/net/horizonsend/ion/server/command/starship/MiscStarshipCommands.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/client/commands/HudCommand.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/client/display/HudIcons.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/gui/custom/settings/SettingsHudGui.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/gui/custom/settings/SettingsHudIconsGui.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Components.kt
- Added additional HUD icons for beacons, stations, and bookmarks
- By default, beacons are enabled while stations and bookmarks are disabled
- Added additional settings for HUD icons (accessible from `/settings`)
=> Hud entities

server/src/main/kotlin/net/horizonsend/ion/server/command/starship/MiscStarshipCommands.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/client/display/HudIcons.kt
- `/jump` (at a HUD icon) is now fixed
- Can now jump to gate and bookmark HUD icons
=> HUD Entities Bug Fixes

server/src/main/kotlin/net/horizonsend/ion/server/configuration/StarshipTypeBalancing.kt
vandrayk asked for this not me
cruiser sdm 3.4 -> 3.7
cruiser shield strenght 1.0 -> 1.1
ion turret range 380 -> 400
=> buff cruisers

server/src/main/kotlin/net/horizonsend/ion/server/features/economy/bazaar/Bazaars.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/gui/custom/bazaar/BazaarPurchaseMenuGui.kt
- now uses anvil gui and number input to prevent spam clicking
=> new bazaar purchase menu

server/src/main/kotlin/net/horizonsend/ion/server/features/misc/AutoRestart.kt
Reduces server announcement spam.
=> Server Reboot Revision

server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/Multiblocks.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/autocrafter/AutoCrafterMultiblock.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/autocrafter/AutoCrafterMultiblockTier1.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/autocrafter/AutoCrafterMultiblockTier2.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/autocrafter/AutoCrafterMultiblockTier3.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/drills/DrillMultiblock.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/drills/DrillMultiblockTier1.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/drills/DrillMultiblockTier2.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/drills/DrillMultiblockTier3.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/mininglasers/MiningLaserMultiblock.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/mininglasers/MiningLaserMultiblockTier1.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/mininglasers/MiningLaserMultiblockTier2.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/mininglasers/MiningLaserMultiblockTier3.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/mininglasers/MiningLaserMultiblockTier4.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/misc/MagazineMultiblock.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/active/SubsystemDetector.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/subsystem/misc/MagazineSubsystem.kt
- The Auto Crafter, Drill, Magazine, and Mining Laser multiblocks can now be mirrored horizontally (the chest's position is on the opposite side)
=> Mirrored multiblocks

server/src/main/kotlin/net/horizonsend/ion/server/command/qol/PersonalTransporterCommand.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/custom/items/CustomItems.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/custom/items/misc/PersonalTransporter.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/custom/items/misc/PersonalTransporterManager.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/gui/GuiItems.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/gui/custom/item/PersonalTransporterGui.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Commands.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Components.kt, server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Listeners.kt
- Adds Personal Transporter
- Players Level 10 and under may consume this item to teleport to any player on the server
- Intended to be included in a one-time kit
=> Personal Transporters (One-Time Teleport)

server/src/main/kotlin/net/horizonsend/ion/server/features/custom/items/CustomItems.kt
- fixed raw ore being bugged
- "bugged" blocks can be placed and will automatically be converted to the correct blocks. contact staff if you need to batch convert
=> Raw Ore Block Fix

server/src/main/kotlin/net/horizonsend/ion/server/listener/misc/ProtectionListener.kt
- Players can now interact with blocks (open chests, activate levers, etc.) within planet orbits
=> Planet orbit protection improvements

server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/misc/TractorBeamMultiblock.kt
=> 2x2 tractor beam

common/src/main/kotlin/net/horizonsend/ion/common/database/cache/nations/PlayerCache.kt, common/src/main/kotlin/net/horizonsend/ion/common/database/schema/misc/SLPlayer.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/chat/ChatChannel.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/chat/messages/NationsChatMessage.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/gui/custom/settings/SettingsMainMenuGui.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/fleet/Fleet.kt
3 diff settings
1. shorten chat channels ( like Settlement -> [S] )
2. remove prefixes (Helper, Contributor) from non-global chats ( global, local, planet, system )
3. remove prefixes (Helper, Contributor) from global chats ( global, local, planet, system )
=> Chat Shortening settings

server/src/main/kotlin/net/horizonsend/ion/server/features/starship/control/weaponry/PlayerStarshipWeaponry.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/control/weaponry/StarshipWeaponry.kt
- Weapon targeting distance will automatically adjust based on a starship the player is aiming at
=> Weapon Convergence

server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Crafting.kt
`moss + pale oak leaves` 
shapeless
=> add pale moss recipe

server/src/main/kotlin/net/horizonsend/ion/server/command/starship/MiscStarshipCommands.kt
also works for uppercase K
works correctly with ~ handling
=> "k" suffix in /jump to multiply coords by 1000

server/src/main/kotlin/net/horizonsend/ion/server/features/nations/NationsMap.kt
(green if nationless)
(only if active)
=> TC border color based on nation color

server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/MultiblockRegistration.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/particleshield/BubbleShieldMultiblock.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/active/SubsystemDetector.kt, server/src/main/kotlin/net/horizonsend/ion/server/features/starship/subsystem/shield/BubbleShieldSubsystem.kt
[shield]
name
w h d
min "side length" of 9, max of 27
=> Added Bubble (Ellipsoid) Shields
