HorizonsEndMC/Ion

- Server/src/main/kotlin/net/horizonsend/ion/server/IonServer.kt
- Server/src/main/kotlin/net/horizonsend/ion/server/listeners/PlayerKickListener.kt
Really dumb solution.
Not sure about `Component#toString()`, but otherwise this should work.
I am a little worried about https://github.com/PaperMC/Paper/issues/8019#issuecomment-1159582582, but a failed command is probably better than a kick.
> Prevent players being kicked due to out of order chat

- Proxy/src/main/kotlin/net/horizonsend/ion/proxy/listeners/PlayerDisconnectListener.kt
- Proxy/src/main/kotlin/net/horizonsend/ion/proxy/listeners/ServerConnectListener.kt
I don't like it, but it should work. 
Hopefully fixes 
but it's untested because I'm too lazy
> Fix underscores in usernames displaying as italics in discord join/leave/switch messages

- Server/src/main/kotlin/net/starlegacy/feature/starship/StarshipType.kt
Server was stress tested and can handle Dreadnoughts but not supercapitals, tps got to 9 with just 1 supercap, aint gone work cuz.
> Remove SuperCapitals from creative

- Server/src/main/kotlin/net/horizonsend/ion/core/ShipFactoryMaterialCosts.kt
Sets price to 0.1 for: stairs, for consistency with other ship hull blocks; full block variants of slabs, for consistency with double slabs; and their chiseled/cracked/decorative variants
> Printing tax consistency

- Server/src/main/kotlin/net/starlegacy/feature/gear/powerarmor/PowerArmorManager.kt
Gives player the water breathing potion effect while wearing a power armor helmet with environment module, since the module currently has no use
> Environmental module water breathing

- Server/src/main/kotlin/net/starlegacy/feature/starship/PilotedStarships.kt
moderators can't check the pilot of starships, normal players find out the pilot by trying to re-detect, if a mod does it just re-detects with "pilot msg" because they have dutymode bypass
> State Pilot Name(helpful for mods)

- Server/src/main/kotlin/net/starlegacy/feature/chat/ChannelSelections.kt
- Server/src/main/kotlin/net/starlegacy/feature/chat/ChatChannel.kt
Fixed the Color Code bug when people
switch chats ("&" color codes were showing up in the action message)
also I tried to fix the AsyncPlayerChatEvent deprication by changing the 
import org.bukkit.event.player.AsyncPlayerChatEvent
to
import io.papermc.paper.event.player.AsyncChatEvent
lots of errors came up that id rather not do rn so i just replaced the "&" color codes with the <> color codes
> Fixed ColorCode bug for Action Msg when switching chat channels

- server/src/main/kotlin/net/horizonsend/ion/server/items/CustomItems.kt
Have all weapon types share cooldown and reload with weapons of the same type (Secondaries, Primaries and later on Heavy)
Encourages people to carry with them sidearms to use whilst primary weapons are off cooldown/reloading
iron_hoe = primary
diamond_hoe = secondaries
netherite_hoe = heavy
> Weapon class shared cooldown/reload

- server/src/main/kotlin/net/horizonsend/ion/server/IonServer.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/whereisit/SearchCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/whereisit/mod/FoundType.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/whereisit/mod/Packets.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/whereisit/mod/SearchResult.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/whereisit/mod/Searcher.kt
- server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/Commands.kt
- server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/Miscellaneous.kt
- server/src/main/kotlin/net/starlegacy/listener/misc/ProtectionListener.kt
This PR adds a very important time saver to the server, it lets players search items in chests via commands or a clientside mod (Where Is It). 
This feature is very useful for people with massive pipe buffers that need to find stuff in them, and is in general a very good QOL addon that not a lot of servers have. (Also, the search method filters out every chest that isn't accessible by the player running it).
Adds Where Is It integration
Adds three commands:
- /itemsearch: Searches the item you are holding.
- /itemsearch <material>: Searches for a vanilla material.
- /itemsearch <legacy/custom> <name>: Searches for a custom item.
The command will highlight the chests in vanilla too with a method I've added (Miscellaneous#highlightBlock)
> feat: Item Search

- server/src/main/kotlin/net/starlegacy/feature/starship/control/StarshipSigns.kt
-to show commands and keybinds for turning and cruising
-teaches new players how to do /cruise and turn without helm sign
> Added text on helm and cruise signs

- server/src/main/kotlin/net/starlegacy/feature/multiblock/dockingtube/ConnectedDockingTubeMultiblock.kt
- server/src/main/kotlin/net/starlegacy/feature/multiblock/dockingtube/DisconnectedDockingTubeMultiblock.kt
> Fix docking tube message formatting

- server/src/main/kotlin/net/horizonsend/ion/server/configuration/BalancingConfiguration.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/blasters/RayTracedParticleProjectile.kt
Non-player living entities now take more damage for guns (default 2.0x). Also added configuration value.
NOTE: Change `balancing.json` by adding `"mobDamageMultiplier": 2.0` to all weapons WHEN UPDATING (ION WILL BREAK IF NOT ADDED)
> Added mob damage multiplier + balancing configuration values

- server/src/main/kotlin/net/starlegacy/feature/starship/hyperspace/HyperspaceMap.kt
Commented out the arrow that appears when jumping to hyperspace. Will be re-implemented as a cone in the future.
> Removed hyperspace jump arrow

- server/src/main/kotlin/net/starlegacy/command/nations/NationCommand.kt
- senderNationId (used for relation check) now returns null instead of failing command (NOT TESTED)
> nation info command fix

- proxy/src/main/kotlin/net/horizonsend/ion/proxy/commands/DiscordCommands.kt
Should fix the issue seen below
(See \_MrBlock_'s username)
Untested as I'm too lazy, but I don't think this will break anything, as it's incredibly minor.
> Escape underscores in usernames in /playerlist

- server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/ShipFactoryMaterialCosts.kt
Lemaire was bugging me about it because apparently her trees are like bankrupting her to print
Thrusters all cost 25.0
many more blocks are added to the 0.1 category
default price of unlisted blocks is 1 instead of 3
> Printing cost changes

- server/src/main/kotlin/net/horizonsend/ion/server/command/starship/StarshipDebugCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/misc/HyperspaceBeaconManager.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/control/StarshipControl.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/event/StarshipEnterHyperspaceEvent.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/event/StarshipExitHyperspaceEvent.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/hyperspace/Hyperspace.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/movement/StarshipMovement.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/movement/StarshipTeleportation.kt
Entering and exiting hyperspace now have events associated with them, allowing for some quality-of-life features:
- Hyperspace beacons are detected immediately upon exiting hyperspace
- Hyperspace jump sounds play correctly for the player that is jumping
> Improved hyperspace events

- server/src/main/kotlin/net/horizonsend/ion/server/features/nations/NationsMasterTasks.kt
Different messages capitalized things differently, which was annoying because its inconsistent.
Also changed it from "Settlement City" to "Player Trade City" because that makes more sense.
Yes this is very much a nitpick, I don't care.
> Fix wording on trade city status notifications

- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/PilotedStarships.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/movement/StarshipMovement.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/subsystem/weapon/projectile/SimpleProjectile.kt
The check for hyperspace dimensions in the tryRelease function checks for capital-H "Hyperspace" in the dimension name. To my knowledge, all hyperspace dimensions on Horizon's End use a lowercase-h (the checks in SimpleProjectile.kt and StarshipMovement.kt also use lowercase-h). Assuming this is the case, this check would return false even in a dimension such as Asteri_hyperspace; now, it will return true.
> changed one character, maybe fixed hyperspace releasing

- server/src/main/kotlin/net/horizonsend/ion/server/configuration/StarshipTypeBalancing.kt
6000 -> 7500 -> 6000, it left a gap between 2001 and 3374 where no LTs would fire on corvettes, just a confusing and unnecessary balancing change
> revert corvette LT power usage upping

- server/src/main/kotlin/net/horizonsend/ion/server/features/customblocks/CustomBlockListeners.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/customitems/commands/ConvertCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/misc/DecomposeTask.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/drills/DrillMultiblock.kt
- server/src/main/kotlin/net/horizonsend/ion/server/listener/gear/PowerToolListener.kt
- Improved Power Drill feedback when breaking custom blocks
- Opening chests/containers containing legacy mineral items will automatically convert them into new custom mineral items
- Fixed mining lasers not collecting custom blocks when in survival mode
- Fixed a duplication glitch
- Removed ability for pickaxes to mine custom ores
- Removed ability for silk touch pickaxes to mine custom ores and drop the original ore block
> Custom blocks hotfix

- server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/MultiblockShape.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/starshipweapon/turret/HeavyTurretMultiblock.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/starshipweapon/turret/LightTurretMultiblock.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/starshipweapon/turret/QuadTurretMultiblock.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/starshipweapon/turret/TriTurretMultiblock.kt
Allow double slabs in place of terracotta in turret multiblocks. This does not allow single slabs in said positions.
> Allow double slabs in turret terracotta positions

- server/src/main/kotlin/net/horizonsend/ion/server/configuration/StarshipTypeBalancing.kt
BC speed ~14 -> ~8 (they were too fast to justify the weapon power) Quad turret power usage 3000 -> 4500 (in attempt to limit the armament of mini BCs and such)
> Revised BC balancing

- server/src/main/kotlin/net/horizonsend/ion/server/features/transport/pipe/Pipes.kt
This pr adds grindstones as pipe blocks, they accept piping from any side but only send onto the side its facing
this means that grindstones are now wildcards that can be put on ships and perfect merges are now a thing
> added merge pipes

- server/src/main/kotlin/net/horizonsend/ion/server/features/sidebar/tasks/ContactsSidebar.kt
- If a player is piloting a starship, the ship's center of mass will now be used to calculate the distance from other objects instead of the player's position. The player position will still be used if not piloted.
- Other starships' center of mass will always be used to calculate the distance to the contacts viewer.
> Contacts Center of Mass Change

- common/src/main/kotlin/net/horizonsend/ion/common/database/cache/nations/PlayerCache.kt
- common/src/main/kotlin/net/horizonsend/ion/common/database/schema/misc/SLPlayer.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/sidebar/command/SidebarCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/sidebar/command/SidebarContactsCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/sidebar/command/SidebarStarshipsCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/sidebar/command/SidebarWaypointsCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/sidebar/component/StarshipsHeaderSidebarComponent.kt
- server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Commands.kt
- Use plain name for starships instead of MiniMessage name
- Station contacts disabled by default (existing users need to change this themselves)
- General info on the sidebar command: `/sidebar`
> Sidebar 2 Hotfix

- server/src/main/kotlin/net/horizonsend/ion/server/command/qol/SetPowerCommand.kt
it sets power with fast as the default, making it not do that
> fix backwards setpower logic

- server/src/main/kotlin/net/horizonsend/ion/server/configuration/StarshipTypeBalancing.kt
Changed AI Corvette shift speed and shift accel from 20 -> 5
This will allow AI Corvettes to have a speed of between 5-35, as opposed to the previous 40-80.
> Update StarshipTypeBalancing.kt (AI Corvette speed balancing

- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/AutoTurretTargeting.kt
- If an auto turret is focused on a player piloting a starship, the turret will target random blocks on the starship instead of the player's location
> Auto Turret Improvement

- server/src/main/kotlin/net/horizonsend/ion/server/features/customitems/CustomItems.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/Multiblocks.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/ammo/AmmoLoaderMultiblock.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/ammo/AmmoPressMultiblock.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/ammo/MissileLoaderMultiblock.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/ammo/StandardAmmoPressMultiblock.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/crafting/MultiblockRecipes.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/subsystem/weapon/primary/IonTurretWeaponSubsystem.kt
- server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Crafting.kt
Missile Loader/Missile Industry Framework, Recipes, (INCOMPLETE, Needs a MultiBlockRecipe that instead of interacting with the furnace, pulls from an external container and outputs in the furnace slot. This is so we can have crafting times for ammo recipes: 90s for Loaded Shell, 1 Hour for Arsenal Missile)
> Battlecruiser - Missile Industry WIP

- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/FlyableBlocks.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/StarshipDetection.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/transport/pipe/Pipes.kt
- Decorated pots have been added to the pipe system. They can store one item (or item stack) and do not have a GUI.
> Decorated Pots

- server/src/main/kotlin/net/horizonsend/ion/server/features/misc/CombatNPCs.kt
- Combat NPCs should now float
- (For some reason, `Gravity.setEnabled(true)` removes gravity)
> Fix Combat NPC Gravity

- server/src/main/kotlin/net/horizonsend/ion/server/configuration/StarshipTypeBalancing.kt
This allows light freighters that are at least 3500 blocks large to fire one light turret.
> Light Freighter - Light Turret Power Usage `6000 -> 5300`

- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/active/ActiveControlledStarship.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/control/movement/StarshipCruising.kt
* Players can now stand on any block in dc without falling though the floor
* Players will not longer experience drift when starting dc
* When hitting cruise while in dc, instead of doing nothing, it will stop dc and start cruise (should help with dc cruise)
* Information about starting cruise displays properly now
> qol dc and cruise changes

- server/src/main/kotlin/net/horizonsend/ion/server/command/qol/ContainerCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Commands.kt
all of these work within worldedit selections
`/container empty` - empties all containers within selection
`/container empty <item>` - removes `item` from all containers within selection
`/container fill <item>` - replaces all empty spaces with `item` to all containers within selection
> add container command

- build.gradle.kts
UnifiedMetrics does not mark it's latest version as being compatible with 1.20.4, however the 1.19.4 version works as intended.
To fix this, I added a override to the `downloadModrinthArtifact` function, allowing 1.19.4 to be specified.
> Fix UnifiedMetrics Version

- server/src/main/kotlin/net/horizonsend/ion/server/command/starship/RainbowProjectileCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/utils/Miscellaneous.kt
Gaymode is really noticeable when people type /g and isn't very descriptive of what it does, leading people to ask questions. You can search in global and check, there is a pretty ridiculous proportion of people asking what it is when we could just have a normal descriptive command. 
Anyway more importantly I made the colors more saturated.
> increase rainbowweapons saturation and rename back to rainbowweapons instead of gaymode

- server/src/main/kotlin/net/horizonsend/ion/server/command/economy/BazaarCommand.kt
- Syntax: `/bazaar forcewithdraw <player> <item>`
- Requires: You own the trade city settlement
- Removes all stock of a player's item at the trade city you are in
> `/bazaar forcewithdraw`

- common/src/main/kotlin/net/horizonsend/ion/common/database/cache/nations/PlayerCache.kt
- common/src/main/kotlin/net/horizonsend/ion/common/database/schema/misc/SLPlayer.kt
- server/src/main/kotlin/net/horizonsend/ion/server/command/admin/CombatTagCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/command/admin/CombatTimerCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/command/misc/CombatTimerCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/command/misc/SuicideCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/command/nations/NationCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/command/nations/SettlementCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/command/nations/SpaceStationCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/configuration/FeatureFlags.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/gui/custom/settings/SettingsOtherGui.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/gui/custom/settings/SettingsSidebarCombatTimerGui.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/npcs/NPCManager.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/npcs/traits/CombatNPCTrait.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/player/CombatNPCs.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/player/CombatTimer.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/sidebar/MainSidebar.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/sidebar/command/SidebarCombatTimerCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/sidebar/component/CombatTagSidebarComponent.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/PilotedStarships.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/Starship.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/damager/Damager.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/movement/StarshipMovement.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/subsystem/weapon/projectile/SimpleProjectile.kt
- server/src/main/kotlin/net/horizonsend/ion/server/listener/misc/ProtectionListener.kt
- server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Commands.kt
- server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Components.kt
- server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/utils/Coordinates.kt
Adds combat timers (combat tags) which prevent players from doing certain actions while in combat. This intends to make combat between NPCs and players more enjoyable.
On certain actions, players will be marked with an NPC combat timer, or a PvP combat timer:
- NPC combat timer:
- Engage in SvS with an NPC ship
- PvP combat timer:
- Engage in SvS with another player's ship
- Engage in PvP with another player
- Be close to an enemy player that is piloting a ship (within 500m)
- Be caught in an enemy player's gravity well
- Cannot be in a safe zone
While marked with a combat timer, certain restrictions are applied to a player:
- NPC combat timer:
- Lasts 2m30s
- Cannot release ship (will be unpiloted instead)
- Cannot claim territory, settlements, or space stations
- Cannot kill yourself
- …
> Combat Timers

- common/src/main/kotlin/net/horizonsend/ion/common/database/schema/nations/SettlementZone.kt
- server/src/main/kotlin/net/horizonsend/ion/server/command/GlobalCompletions.kt
- server/src/main/kotlin/net/horizonsend/ion/server/command/nations/settlementZones/SettlementPlotCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/nations/region/types/RegionSettlementZone.kt
- server/src/main/kotlin/net/horizonsend/ion/server/listener/misc/ProtectionListener.kt
- server/src/main/kotlin/net/horizonsend/ion/server/listener/nations/FriendlyFireListener.kt
Adds a feature to allow certain blocks within settlement zones to be interacted with by anyone
- `/splot interactableblocks add <zone> <block>` allows all blocks of the same type in the settlement zone to be interacted with by anyone
- `/splot interactableblocks remove <zone> <block>` removes the block
- `/splot interactableblocks list <zone>`
- Only blocks with the InventoryHolder, Openable, Switch, and Powerable property will be affected at this time
> Settlement Zone Interactable Blocks

- server/src/main/kotlin/net/horizonsend/ion/server/command/qol/SearchCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/client/display/ClientDisplayEntities.kt
new features:
* typing `/itemsearch` with no parameters will now search for the item in the player's main hand
bugfixes:
* searching double chests will now display a normal chest with the type `SINGLE` instead of the `LEFT` and `RIGHT` types
* this fixes weird culling issues with the Display Entities
* double chests are now treated as unconnected chests
* if an item is in the top half of the inventory, it exists within the LEFT chest
* if an item is in the bottom half of the inventory, it exists within the RIGHT chest
* this fixes the issue of "2 containers found" always triggering for double chests
> itemsearch bugfixes & code cleanup

- server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/utils/Discord.kt
In death messages, player heads are being displayed as images rather then thumbnails, this makes them rather big, distracting, and space consuming.
This PR fixes this by changing the thumbnail property to actually use `setThumbnail` rather then `setImage`, deflating player heads.
> Deflate Player Heads on Discord

- server/src/main/kotlin/net/horizonsend/ion/server/command/misc/CombatTimerCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/command/nations/SpaceStationCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/command/starship/StarshipInfoCommand.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/custom/items/powered/PowerDrill.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/machine/decomposer/Decomposers.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/multiblock/type/drills/DrillMultiblock.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/player/CombatTimer.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/Interdiction.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/control/movement/StarshipControl.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/factory/StarshipFactories.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/hyperspace/MassShadows.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/movement/PlanetTeleportCooldown.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/movement/StarshipMovement.kt
- server/src/main/kotlin/net/horizonsend/ion/server/features/starship/subsystem/misc/MiningLaserSubsystem.kt
- server/src/main/kotlin/net/horizonsend/ion/server/listener/misc/ProtectionListener.kt
- server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Components.kt
- Starships cannot enter or exit planet if the player is combat tagged and the player has previously entered or exited the planet in the past 2 minutes
- Cannot build in the path of a planet's orbit within 500 blocks, unless within a space station
- Cannot claim space stations within `130 -> 500` blocks of a planet's orbit
- Cannot claim space stations within 200 blocks of another space station
- Ship drills, decomposers, and ship factories cannot be used while in combat
- Interdiction range is now based on an equation
- Improved the consistency of planet entry and exit positions
- Fixed a bug where resizing stations did not work as intended
> Balancing changes

- server/src/main/kotlin/net/horizonsend/ion/server/features/client/display/modular/BlockDisplayWrapper.kt
- server/src/main/kotlin/net/horizonsend/ion/server/miscellaneous/registrations/Crafting.kt
added a "brightness" value under the .apply for the block entities that make up the turret model, set it to 15 for both sky and block brightness. this will prevent the custom turrets appearing black when the ship is active, i plan on testing custom light levels for the turret based on the light surrounding it upon ship redection, unsure if it will look good, need to test it.
> fix for custom turret rendering

- server/src/main/kotlin/net/horizonsend/ion/server/command/starship/MiscStarshipCommands.kt
this is such a little thing, but it is something i am able to help with :)
i changed the message "Destination coordinates are outside the world order"
to "Destination coordinates are outside the world border!"
> Typo fix for when jump coordinates are outside of the world border

- server/src/main/kotlin/net/horizonsend/ion/server/features/machine/GeneratorFuel.kt
Fixes a bug where dried kelp doesn't work in the generator, and overriding the proper value for dried kelp block.
> Fix DRIED_KELP and DRIED_KELP_BLOCK to have the correct values.

- server/src/main/kotlin/net/horizonsend/ion/server/configuration/StarshipTypeBalancing.kt
Temporary nerf to LCs, puts them on par with other ships at 1k only. 
They will be worse than normal weapons on every other ship.
> LC power consumption 240 -> 600
